caterwaul.module( 'parser' ,function($) { (function( ) {var memoization_key=$.gensym( 'memo' ) ,memo_id=0,memo_single=function(f,state) {;
return(function( ) {var f_key=f[memoization_key] || (f[memoization_key] = ++memo_id) ,s_key=state.id() ,table=state.memo_table() ,key= ( '@' + (s_key) + '_' + (f_key) + '' ) ,value=f_key&&s_key&&table.hasOwnProperty(key) ?table[key] : (table[key] =f( [state] ) ) ;
return(value) } ) .call(this) } ,memo=function(f,states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (memo_single(f,x) ) ) ) ;
return xr} ) .call(this,states) } ,parsers=function(name,xs) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (x.caterwaul_parser|| (function( ) {throw new Error( ( '' + (name) + ': ' + (x) + ' is not marked with the .caterwaul_parser attribute' ) ) } ) .call(this) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (x instanceof Array?x: [x] ) ) ) ;
return xr} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (x|| (function( ) {throw new Error( ( '' + (name) + ': undefined parser given as parameter ' + (xi) + '' ) ) } ) .call(this) ) ;
return xs} ) .call(this,Array.prototype.slice.call( (xs) ) ) ) ) } ,annotate=function(f,name,xs) {;
return(function(it) {return(xs=xs|| [ ] ,it.toString=function() {;
return( '' + (name) + '(' + ( (function(it) {return(it.join( ", " ) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.toString() ) ) ;
return xr} ) .call(this,xs) ) ) ) + ')' ) } ,it.caterwaul_parser=true) ,it} ) .call(this, (f) ) } ;
return($.parser= {annotate:annotate,parsers:parsers} ,$.merge($.parser, (function( ) {var bfs=function() {var ps=parsers( 'bfs' ,arguments) ;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (states) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (memo(x,x0) ) ;
return x0} ) .call(this,ps) } ;
 (annotate(result, 'bfs' ,ps) ) ;
return result} ,bfc=function() {var ps=parsers( 'bfc' ,arguments) ;
var result=function(states) {;
return row_composite_states_from( (function(xs) {var x,x0,xi,xl,xr;
for(var x0= (state_matrix(states) ) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (step_matrix_mutable(x) (x0) ) ;
return x0} ) .call(this,ps) ) } ;
 (annotate(result, 'bfc' ,ps) ) ;
return result} ,state_matrix=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x] ) ) ;
return xr} ) .call(this,states) } ,step_matrix_mutable=function(p) {;
return function(m) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length;
ri<rl;
 ++ri)r=rs[ri] ,rr.push.apply(rr,Array.prototype.slice.call( ( (function( ) {var xs=memo_single(p,r[r.length-1] ) ;
return(xs.length===1?r.push(xs[0] ) && [r] : (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (r) .concat( ( [x] ) ) ) ) ;
return xr} ) .call(this,xs) ) } ) .call(this) ) ) ) ;
return rr} ) .call(this,m) } } ,step_matrix_immutable=function(p) {;
return function(m) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length;
ri<rl;
 ++ri)r=rs[ri] ,rr.push.apply(rr,Array.prototype.slice.call( ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (r) .concat( ( [x] ) ) ) ) ;
return xr} ) .call(this,memo_single(p,r[r.length-1] ) ) ) ) ) ;
return rr} ) .call(this,m) } } ,row_composite_states_from=function(m) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length;
ri<rl;
 ++ri)r=rs[ri] ,rr.push( (r[r.length-1] .map(function(_) {return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.value() ) ) ;
return xr} ) .call(this,r.slice(1,r.length) ) } ) ) ) ;
return rr} ) .call(this,m) } ,alt=function() {var ps=parsers( 'alt' ,arguments) ;
var result=function(states) {;
return(function(states) {var state,state0,statei,statel,stater;
for(var stater=new states.constructor() ,statei=0,statel=states.length;
statei<statel;
 ++statei)state=states[statei] ,stater.push.apply(stater,Array.prototype.slice.call( ( (function(ps) {var p,p0,pi,pl,pr;
for(var p=ps[0] ,pi=0,pl=ps.length,x1;
pi<pl;
 ++pi) {p=ps[pi] ;
if(x1= ( (function(it) {return(it.length&&it) } ) .call(this, (memo_single(p,state) ) ) ) )return x1}return false} ) .call(this,ps) || [ ] ) ) ) ;
return stater} ) .call(this,states) } ;
 (annotate(result, 'alt' ,ps) ) ;
return result} ,all=function() {var ps=parsers( 'all' ,arguments) ;
var result=function(states) {;
return(function(states) {var state,state0,statei,statel,stater;
for(var stater=new states.constructor() ,statei=0,statel=states.length;
statei<statel;
 ++statei)state=states[statei] ,stater.push.apply(stater,Array.prototype.slice.call( ( (function(ps) {var p,p0,pi,pl,pr;
for(var pr=new ps.constructor() ,pi=0,pl=ps.length;
pi<pl;
 ++pi)p=ps[pi] ,pr.push.apply(pr,Array.prototype.slice.call( (memo_single(p,state) ) ) ) ;
return pr} ) .call(this,ps) ) ) ) ;
return stater} ) .call(this,states) } ;
 (annotate(result, 'all' ,ps) ) ;
return result} ,manyc=function(p) {;
var result=function(states) {;
return(function( ) {var iterate=step_matrix_mutable_null(p) ,step=function(m) {;
return has_non_null_states(m) ?iterate(m) :null} ;
return(row_null_states_from( (function(xs1) {var x2,x01,xi1,xl1,xr1;
for(var xr1= [ ] ,x2=xs1,xi1=0;
x2!==null;
 ++xi1)xr1.push(x2) ,x2= (step(x2) ) ;
return xr1} ) .call(this,state_matrix(states) ) ) ) } ) .call(this) } ;
 (annotate(result, 'manyc' , [p] ) ) ;
return result} ,manyc_one=function(p) {;
return map(bfc(p,manyc(p) ) ,function(_) {return( [_[0] ] ) .concat( (_[1] ) ) } ) } ,many=function(p,join) {;
var result= (function( ) {var j=join||bfs,f=function(states) {;
return f(states) } ,f=alt(j(p,annotate(f, 'recursive' , [ ] ) ) ,p) ;
return(f) } ) .call(this) ;
 (annotate(result, 'many' , [p,join] ) ) ;
return result} ,optional=function(p) {;
var result=alt(p,zero() ) ;
 (annotate(result, 'optional' , [p] ) ) ;
return result} ,step_matrix_immutable_null=function(p) {;
return function(m) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length;
ri<rl;
 ++ri)r=rs[ri] ,rr.push.apply(rr,Array.prototype.slice.call( ( (function( ) {var xs= (function(it) {return(it&&memo_single(p,it) ) } ) .call(this, (r[r.length-1] ) ) ;
return(xs?xs.length? (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (r) .concat( ( [x] ) ) ) ) ;
return xr} ) .call(this,xs) : [ (r) .concat( ( [null] ) ) ] : [r] ) } ) .call(this) ) ) ) ;
return rr} ) .call(this,m) } } ,step_matrix_mutable_null=function(p) {;
return function(m) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length;
ri<rl;
 ++ri)r=rs[ri] ,rr.push.apply(rr,Array.prototype.slice.call( ( (function( ) {var xs= (function(it) {return(it&&memo_single(p,it) ) } ) .call(this, (r[r.length-1] ) ) ,l=xs&&xs.length;
return(xs?l?l===1?r.push(xs[0] ) && [r] : (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (r) .concat( ( [x] ) ) ) ) ;
return xr} ) .call(this,xs) :r.push(null) && [r] : [r] ) } ) .call(this) ) ) ) ;
return rr} ) .call(this,m) } } ,has_non_null_states=function(m) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var r=rs[0] ,ri=0,rl=rs.length,x1;
ri<rl;
 ++ri) {r=rs[ri] ;
if(x1= (r[r.length-1] ) )return x1}return false} ) .call(this,m) } ,row_null_states_from=function(ms) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length;
ri<rl;
 ++ri)r=rs[ri] ,rr.push( (r[r.length-2] .map(function(_) {return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.value() ) ) ;
return xr} ) .call(this,r.slice(1,r.length-1) ) } ) ) ) ;
return rr} ) .call(this,ms[ms.length-1] ) } ,zero=function() {;
var result=function(states) {;
return states} ;
 (annotate(result, 'zero' , [ ] ) ) ;
return result} ,fail=function() {;
var result=function(states) {;
return[ ] } ;
 (annotate(result, 'fail' , [ ] ) ) ;
return result} ,match=function(p) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (memo_single(p,x) .length) &&xr.push(x) ;
return xr} ) .call(this,states) } ;
 (annotate(result, 'match' , [p] ) ) ;
return result} ,reject=function(p) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (memo_single(p,x) .length) ||xr.push(x) ;
return xr} ) .call(this,states) } ;
 (annotate(result, 'reject' , [p] ) ) ;
return result} ,pluralize=function(p) {;
var result=function(states) {;
return(function(xs1) {var x2,x01,xi1,xl1,xr1;
for(var xr1=new xs1.constructor() ,xi1=0,xl1=xs1.length,_y;
xi1<xl1;
 ++xi1)x2=xs1[xi1] , (_y= (p(x2) ) ) &&xr1.push(_y) ;
return xr1} ) .call(this,states) } ;
 (annotate(result, 'pluralize' , [p] ) ) ;
return result} ,iv=function(f) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.change( {value:f(x.input() ,x.position() ) } ) ) ) ;
return xr} ) .call(this,states) } ;
 (annotate(result, 'iv' , [f] ) ) ;
return result} ,map=function(p,f) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.map(f) ) ) ;
return xr} ) .call(this,p(states) ) } ;
 (annotate(result, 'map' , [p,f] ) ) ;
return result} ,flat_map=function(p,f) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( ( (function(ys) {var y,y0,yi,yl,yr;
for(var yr=new ys.constructor() ,yi=0,yl=ys.length;
yi<yl;
 ++yi)y=ys[yi] ,yr.push( (x.map(delay in y) ) ) ;
return yr} ) .call(this,f(x.value() ) ) ) ) ) ;
return xr} ) .call(this,p(states) ) } ;
 (annotate(result, 'flat_map' , [p,f] ) ) ;
return result} ,map_state=function(p,f) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (f(x) ) ) ;
return xr} ) .call(this,p(states) ) } ;
 (annotate(result, 'map_state' , [p,f] ) ) ;
return result} ,flat_map_state=function(p,f) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (f(x) ) ) ) ;
return xr} ) .call(this,p(states) ) } ;
 (annotate(result, 'flat_map_state' , [p,f] ) ) ;
return result} ;
return( {bfs:bfs,bfc:bfc,state_matrix:state_matrix,step_matrix_mutable:step_matrix_mutable,step_matrix_immutable:step_matrix_immutable,row_composite_states_from:row_composite_states_from,alt:alt,all:all,manyc:manyc,manyc_one:manyc_one,many:many,optional:optional,step_matrix_immutable_null:step_matrix_immutable_null,step_matrix_mutable_null:step_matrix_mutable_null,has_non_null_states:has_non_null_states,row_null_states_from:row_null_states_from,zero:zero,fail:fail,match:match,reject:reject,pluralize:pluralize,iv:iv,map:map,flat_map:flat_map,map_state:map_state,flat_map_state:flat_map_state} ) } ) .call(this) ) ,$.parser.logical_state=function(options) {;
return(function( ) {var defaults=options.defaults|| { } ,default_position=defaults.position,default_value=defaults.value,id_function=defaults.id||function(_) {return++memo_id} ,ctor=function(i,p,v,memo_table) {;
return arguments.length>1? (function(it) {return(it.i=i,it.p=p,it.v=v,it.table=memo_table) ,it} ) .call(this, (this) ) : (function(it) {return(it.i=i,it.p=default_position,it.v=default_value,it.table= { } ) ,it} ) .call(this, (this) ) } ,methods_for=function(step) {;
return{id:function() {;
return this.cached_id|| (this.cached_id=id_function.call(this) ) } ,input:function() {;
return this.i} ,next:function(n,v) {;
return n===1?step.call(this,this.p,v) : (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (x.next(1,v) ) ) ) ;
return xr} ) .call(this,this.next(n-1,v) ) } ,position:function() {;
return this.p} ,map:function(f) {;
return new this.constructor(this.i,this.p,f(this.v) ,this.table) } ,value:function() {;
return this.v} ,memo_table:function() {;
return this.table} ,toString:function() {;
return( '' + (this.i) + ' @ ' + (this.p) + ' : ' + (this.v) + '' ) } ,change:function(values) {;
return new this.constructor( 'input'in values?values.input:this.i, 'position'in values?values.position:this.p, 'value'in values?values.value:this.v,this.table) } } } ;
return( (function(it) {return($.merge(it.prototype,methods_for(options.step) ) ) ,it} ) .call(this, (ctor) ) ) } ) .call(this) } ,$.parser.linear_string_state=$.merge($.parser.logical_state( {step:function(p,v) {;
return[this.change( {position:p+1,value:v} ) ] } ,id:function() {;
return this.position() } ,defaults: {position:0} } ) , {end:function() {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (x.position() ===x.input() .length) &&xr.push(x) ;
return xr} ) .call(this,states) } ;
 (annotate(result, 'end' , [ ] ) ) ;
return result} } ) ,$.merge($.parser, {anchor_regexp:function(r) {;
return(function( ) {var pieces= /^\/(.*)\/(\w*)$/ .exec(r.toString() ) ,body=pieces[1] ,flags=pieces[2] ;
return(new RegExp( ( '^' + (body) + '$' ) ,flags) ) } ) .call(this) } ,linear_string:function(s) {;
var result=function(states) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (x.input() .substr(x.position() ,s.length) ===s?x.next(s.length,s) : [ ] ) ) ) ;
return xr} ) .call(this,states) } ;
 (annotate(result, 'linear_string' , [s] ) ) ;
return result} ,linear_regexp:function(r) {;
var result= (function( ) {var minimum_length=$.regexp(r) .minimum_length() || (function( ) {throw new Error( ( "regexp must require at least one character: " + (r) + "" ) ) } ) .call(this) ,anchored=$.parser.anchor_regexp(r) ,matcher=function(states) {;
return(function(xs1) {var x2,x01,xi1,xl1,xr1;
for(var xr1=new xs1.constructor() ,xi1=0,xl1=xs1.length;
xi1<xl1;
 ++xi1)x2=xs1[xi1] ,xr1.push.apply(xr1,Array.prototype.slice.call( (match_one(x2) ) ) ) ;
return xr1} ) .call(this,states) } ,match_one=function(state) {;
return(function( ) {var s=state.input() ,offset=state.position() ,maximum_length=s.length-offset,match=function(l) {;
return l<=maximum_length&&anchored.test(s.substr(offset,l) ) } ,longest=function(l) {;
return match(l) ?longest(l<<1) :l} ,valid=function(l,m,u) {;
return l<u-1?match(m) ?valid(m,m+u>>1,u) :valid(l,l+m>>1,m) :m} ,new_states=match(minimum_length) ? (function( ) {var max=longest(minimum_length) ,match_length=valid(minimum_length,minimum_length+max>>1,max) ;
return(state.next(match_length,anchored.exec(s.substr(offset,match_length) ) ) ) } ) .call(this) : [ ] ;
return(new_states) } ) .call(this) } ;
return(matcher) } ) .call(this) ;
 (annotate(result, 'linear_regexp' , [r] ) ) ;
return result} } ) ,$.parser.structure_state=$.parser.logical_state( {step:function(p,v) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (this.change( {value:v,input:x[1] ,position:x[0] } ) ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (this.input() ) ) ) } } ) ,$.parser.array_state=$.parser.logical_state( {step:function(p,v) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (this.change( {value:v,input:x,position:xi} ) ) ) ;
return xr} ) .call(this,Array.prototype.slice.call( (this.input() ) ) ) } } ) ,$.merge( ($.parser.proxy_state=function(s,value_function) {;
return(function(it) {return(it.state=s,it.value_function=value_function) ,it} ) .call(this, (this) ) } ) .prototype, {id:function() {;
return this.cached_id|| (this.cached_id= ++memo_id) } ,input:function() {;
return this.value_function.call(this) } ,next:function(n,v) {;
return this.state.next(n,v) } ,position:function() {;
return this.state.position() } ,map:function(f) {;
return this.state.map(f) } ,value:function() {;
return this.state.value() } ,memo_table:function() {;
return this.state.memo_table() } } ) ,$.merge($.parser, {position_state:function(s) {;
return new $.parser.proxy_state(s,function(_) {return this.position() } ) } ,position:function(p) {;
return function(states) {;
return p( (function(xs1) {var x2,x01,xi1,xl1,xr1;
for(var xr1=new xs1.constructor() ,xi1=0,xl1=xs1.length;
xi1<xl1;
 ++xi1)x2=xs1[xi1] ,xr1.push( ($.parser.position_state(x2) ) ) ;
return xr1} ) .call(this,states) ) } } } ) ) } ) .call(this) } ) ;
